env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  no-case-declarations: off
  quotes:
    - error
    - single
  semi:
    - error
    - never
