image: node:latest

cache:
  paths:
    - node_modules/

services:
  - rethinkdb:latest
  - redis:latest

before_script:
  - npm install
  - npm install --only=dev
  - node scripts/migrateDB.js

test:
  script:
    - npm test
