image: node:8

cache:
  paths:
    - node_modules/

services:
  - rethinkdb:latest
  - redis:latest

before_script:
  - npm install
  - npm install --only=dev
  - npm install -g mocha chai
  - node scripts/migrateDB.js

test:
  script:
    - npm install -g codecov
    - npm run build
    - npm test && codecov

test:node:9:
  image: node:9
  script:
    - npm run build
    - npm test