language: node_js
node_js:
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"

addons:
  rethinkdb: "2.3"

services:
  - redis-server

before_script:
  - npm install
  - npm install --only=dev
  - npm install -g mocha chai
  - node scripts/migrateDB.js
  
script:
  - npm test
