language: node_js
node_js:
  - "8"
  - "9"

cache:
  directories:
    - "node_modules"

services:
  - rethinkdb
  - redis

before_script:
  - npm install
  - npm install --only=dev
  - npm install -g mocha chai
  - node scripts/migrateDB.js
  
script:
  - npm test
